### ISSUE TITLE
Lab not showing

### ISSUE THREAD

**Issue by musmanghani1** [Hamza5743/TimeTableGenerator#9]
It is not showing OS lab for section C

**Comment by Hamza5743** [comment]
![image](https://user-images.githubusercontent.com/53045133/153744998-024d0a44-85e1-4ab3-b4de-f917afa70b4c.png)
I just checked and it is being shown. Kindly see if you have unchecked its time or try opening the Generator in incognito window.
If the issue is still not resolved kindly attach a screenshot of your configuration.

**Comment by musmanghani1** [comment]
![image](https://user-images.githubusercontent.com/95126760/153766263-6e8be1b3-7627-4f68-9b34-a01b46a87718.png)
![image](https://user-images.githubusercontent.com/95126760/153766274-380c54ee-e326-4593-b53a-1805fc2a09b4.png)
